version: '3'
services:
  homeassistant:
    container_name: home-assistant
    #image: homeassistant/home-assistant
    build:
      context: .
    network_mode: host
    volumes:
      - /srv/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always

